### ISSUE TITLE
django.template.exceptions.TemplateSyntaxError: 'counter' argument to 'blocktranslate' tag must be a number.

### ISSUE THREAD

**Issue by dacx** [HealthyFridge/django-extended-history#1]
Hey,

first issue! Wanted to say big thanks for providing this.

However, the currently released version on pypi (1.0.0) does not work out of the box for me. I got a problem with the counter argument in the blocktrans section, see this line: https://github.com/HealthyFridge/django-extended-history/blob/main/django_extended_history/templates/object_history.html#L39

To solve the issue for me, I overrode `templates/object_history.html` and removed the blocktrans section altogether. 

Is this something that's somehow unique to me, or did someone else see this as well? I dropped this app into a rather big project with millions of db rows, but that shouldn't be a factor.

**Comment by HealthyFridge** [comment]
Hi, 

nice to hear you're using django-extended-history.

`templates/object_history.html` is a slightly modified copy of `/django/contrib/admin/templates/admin/object_history.html` from Django 4.1 and above.

Upon researching I found Django versions below 4.1 do not support pagination, so it seems I erroneously set the minimal version of Django to 4.0.
My guess is you are using Django >4.0,<4.1, correct?

**Comment by dacx** [comment]
Great catch, it's indeed 4.0.9.

**Comment by HealthyFridge** [comment]
Great! Thanks for helping me figuring out this issue. 
I have not created a fix for Django 4.0, since official support has ended last april. Please continue using your workaround.
A new package with Django >=4.1 as a requirement has been released.
